# Generated by Django 5.0.2 on 2024-04-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_calendarevent'),
        ('project', '0003_conversation_conversationmessage'),
    ]

    operations = [
    ]
