# Generated by Django 5.0.2 on 2024-04-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_merge_20240420_1657'),
        ('project', '0005_mappin'),
    ]

    operations = [
    ]
