# Generated by Django 5.0.2 on 2024-04-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_merge_20240420_1249'),
        ('project', '0006_merge_0004_merge_20240420_1657_0005_mappin'),
    ]

    operations = [
    ]
